// Per-exercise movement captions (bilingual), extracted from the legacy
// hand-drawn animation system. Every one of the 136 exercises — including
// supported / progressed variants — gets its own EN + AR movement cue,
// rendered under the verified pose figures from src/lib/illustrations.ts.

import type { Exercise } from './clinical';

export const animationFor: Record<string, string> = {
  // lower-back – 17
  'lower-back-1': 'breathe-supine',
  'lower-back-2': 'pelvic-tilt',
  'lower-back-3': 'knee-rock',
  'lower-back-4': 'prone-press',
  'lower-back-5': 'brace-supine',
  'lower-back-6': 'heel-slide',
  'lower-back-7': 'bridge',
  'lower-back-8': 'birddog-prep',
  'lower-back-9': 'sit-stand',
  'lower-back-10': 'hinge',
  'lower-back-11': 'bridge-march',
  'lower-back-12': 'birddog-full',
  'lower-back-13': 'chair-squat',
  'lower-back-14': 'weighted-hinge',
  'lower-back-15': 'suitcase-carry',
  'lower-back-1-supported': 'breathe-supine-supported',
  'lower-back-15-progressed': 'suitcase-carry-loaded',
  // neck – 17
  'neck-1': 'neck-rest',
  'neck-2': 'neck-turn',
  'neck-3': 'chin-nod',
  'neck-4': 'neck-hold-rotate',
  'neck-5': 'shoulder-roll',
  'neck-6': 'chin-tuck',
  'neck-7': 'neck-rotate-full',
  'neck-8': 'neck-isometric',
  'neck-9': 'wall-slide',
  'neck-10': 'band-row',
  'neck-11': 'chin-tuck-standing',
  'neck-12': 'resisted-rotation',
  'neck-13': 'incline-push',
  'neck-14': 'band-pullapart',
  'neck-15': 'overhead-reach',
  'neck-1-supported': 'neck-rest-supported',
  'neck-15-progressed': 'overhead-reach-loaded',
  // shoulder – 17
  'shoulder-1': 'shoulder-rest',
  'shoulder-2': 'pendulum',
  'shoulder-3': 'table-slide',
  'shoulder-4': 'scap-set',
  'shoulder-5': 'er-hold',
  'shoulder-6': 'assisted-elevation',
  'shoulder-7': 'wall-slide-shoulder',
  'shoulder-8': 'band-er',
  'shoulder-9': 'scaption',
  'shoulder-10': 'wall-push',
  'shoulder-11': 'er-standing',
  'shoulder-12': 'band-row-shoulder',
  'shoulder-13': 'incline-push-shoulder',
  'shoulder-14': 'weighted-scaption',
  'shoulder-15': 'overhead-press',
  'shoulder-1-supported': 'shoulder-rest-supported',
  'shoulder-15-progressed': 'overhead-press-loaded',
  // knee – 17
  'knee-1': 'knee-rest',
  'knee-2': 'knee-extension-hold',
  'knee-3': 'heel-slide-knee',
  'knee-4': 'quad-set',
  'knee-5': 'seated-knee-bend',
  'knee-6': 'seated-knee-extension',
  'knee-7': 'high-sit-stand',
  'knee-8': 'low-step-up',
  'knee-9': 'mini-squat',
  'knee-10': 'slow-knee-extension',
  'knee-11': 'chair-squat-knee',
  'knee-12': 'step-down',
  'knee-13': 'split-squat',
  'knee-14': 'weighted-squat',
  'knee-15': 'single-leg-sit-stand',
  'knee-1-supported': 'knee-rest-supported',
  'knee-15-progressed': 'single-leg-sit-stand-loaded',
  // hip – 17
  'hip-1': 'hip-rest',
  'hip-2': 'hip-roll',
  'hip-3': 'glute-set',
  'hip-4': 'hip-abduction-hold',
  'hip-5': 'seated-hip-rotation',
  'hip-6': 'bridge-hip',
  'hip-7': 'hip-abduction',
  'hip-8': 'high-chair-hip',
  'hip-9': 'low-step-hip',
  'hip-10': 'hinge-hip',
  'hip-11': 'single-bridge',
  'hip-12': 'lateral-step-up',
  'hip-13': 'split-squat-hip',
  'hip-14': 'weighted-hinge-hip',
  'hip-15': 'lateral-step-down',
  'hip-1-supported': 'hip-rest-supported',
  'hip-15-progressed': 'lateral-step-down-loaded',
  // ankle – 17
  'ankle-1': 'ankle-rest',
  'ankle-2': 'ankle-pump',
  'ankle-3': 'ankle-circle',
  'ankle-4': 'calf-hold',
  'ankle-5': 'toe-spread',
  'ankle-6': 'seated-heel-raise',
  'ankle-7': 'double-calf',
  'ankle-8': 'band-eversion',
  'ankle-9': 'balance-supported',
  'ankle-10': 'heel-lowering',
  'ankle-11': 'single-calf',
  'ankle-12': 'step-calf',
  'ankle-13': 'balance-reach',
  'ankle-14': 'loaded-calf',
  'ankle-15': 'quick-calf',
  'ankle-1-supported': 'ankle-rest-supported',
  'ankle-15-progressed': 'quick-calf-loaded',
  // elbow / wrist / hand – 17
  'elbow-1': 'wrist-rest',
  'elbow-2': 'wrist-circle',
  'elbow-3': 'wrist-hold-extension',
  'elbow-4': 'hand-open',
  'elbow-5': 'thumb-slide',
  'elbow-6': 'wrist-extension',
  'elbow-7': 'wrist-flexion',
  'elbow-8': 'forearm-rotation',
  'elbow-9': 'towel-grip',
  'elbow-10': 'eccentric-wrist',
  'elbow-11': 'loaded-wrist-extension',
  'elbow-12': 'loaded-wrist-flexion',
  'elbow-13': 'towel-twist',
  'elbow-14': 'farmer-carry-elbow',
  'elbow-15': 'pinch-release',
  'elbow-1-supported': 'wrist-rest-supported',
  'elbow-15-progressed': 'pinch-release-loaded',
  // upper-back / thoracic – 17
  'upper-back-1': 'rib-breathing',
  'upper-back-2': 'shoulder-roll-upper',
  'upper-back-3': 'thoracic-rotation',
  'upper-back-4': 'scap-upper',
  'upper-back-5': 'chest-opening',
  'upper-back-6': 'thoracic-extension',
  'upper-back-7': 'open-book',
  'upper-back-8': 'wall-slide-upper',
  'upper-back-9': 'band-row-upper',
  'upper-back-10': 'thoracic-rotation-standing',
  'upper-back-11': 'band-pullapart-upper',
  'upper-back-12': 'prone-arm-lift',
  'upper-back-13': 'resisted-row-upper',
  'upper-back-14': 'rotation-press',
  'upper-back-15': 'overhead-reach-upper',
  'upper-back-1-supported': 'rib-breathing-supported',
  'upper-back-15-progressed': 'overhead-reach-upper-loaded',
};

const labelEn: Record<string, string> = {
  'breathe-supine': 'Breathe into the ribs, let the belly soften',
  'breathe-supine-supported': 'Breathe with extra pillow, even softer',
  'pelvic-tilt': 'Gently rock the pelvis, flatten the low back',
  'knee-rock': 'Knees rock side to side, small and easy',
  'prone-press': 'Press gently onto forearms, pelvis stays soft',
  'brace-supine': 'Lightly brace as if for a gentle nudge',
  'heel-slide': 'Slide heel toward you, then away with control',
  'bridge': 'Press through feet, lift hips without arching',
  'birddog-prep': 'Slide one leg back, pelvis stays level',
  'sit-stand': 'Nose over toes, press through both feet to stand',
  'hinge': 'Hips back, back flat, then drive hips forward',
  'bridge-march': 'Hold bridge, lift one knee a little',
  'birddog-full': 'Opposite arm and leg reach, hold steady',
  'chair-squat': 'Sit back as if to a chair, chest proud',
  'weighted-hinge': 'Hinge with weight close, flat back',
  'suitcase-carry': 'Stand tall, carry close, walk steady',
  'suitcase-carry-loaded': 'Carry a little heavier, same tall posture',
  'neck-rest': 'Support the neck, let the muscles soften',
  'neck-rest-supported': 'Neck on towel, fully supported',
  'neck-turn': 'Turn the head small, eyes follow',
  'chin-nod': 'Small nod – chin glides down, not poking',
  'neck-hold-rotate': 'Turn against hand, hold, breathe',
  'shoulder-roll': 'Roll shoulders back and down, neck easy',
  'chin-tuck': 'Glide chin straight back, lengthen the neck',
  'neck-rotate-full': 'Rotate fully within comfort, slow',
  'neck-isometric': 'Press head into hand, no movement',
  'wall-slide': 'Forearms slide up the wall, ribs stay down',
  'band-row': 'Elbows drive back, shoulder blades together',
  'chin-tuck-standing': 'Standing chin glide, tall posture',
  'resisted-rotation': 'Hand resists gentle turning',
  'incline-push': 'Hands on wall, chest lowers with control',
  'band-pullapart': 'Band apart at chest height, squeeze blades',
  'overhead-reach': 'Reach overhead, ribs stay soft',
  'overhead-reach-loaded': 'Reach with a light load, control down',
  'shoulder-rest': 'Arm supported, let the shoulder settle',
  'shoulder-rest-supported': 'Arm on pillow, shoulder fully eased',
  'pendulum': 'Let the arm hang, body makes the swing',
  'table-slide': 'Hand slides forward on the towel',
  'scap-set': 'Blades gently together then relax',
  'er-hold': 'Elbow at side, press outward into hand',
  'assisted-elevation': 'Other arm helps lift, lower slowly',
  'wall-slide-shoulder': 'Arm slides up wall within comfort',
  'band-er': 'Elbow tucked, rotate out against band',
  'scaption': 'Thumbs up, lift in scapular plane to shoulder height',
  'wall-push': 'Chest to wall and press away slowly',
  'er-standing': 'Standing external rotation, no trunk twist',
  'band-row-shoulder': 'Band row, elbows close',
  'incline-push-shoulder': 'Incline push, body in line',
  'weighted-scaption': 'Light weight scaption, control down 3s',
  'overhead-press': 'Press overhead, neck stays relaxed',
  'overhead-press-loaded': 'Press with a little more load',
  'knee-rest': 'Knee supported, let it settle',
  'knee-rest-supported': 'Knee on pillow, fully eased',
  'knee-extension-hold': 'Tighten front thigh, straighten gently',
  'heel-slide-knee': 'Heel slides in, knee bends comfortably',
  'quad-set': 'Press knee gently down, quad tightens',
  'seated-knee-bend': 'Foot slides back, knee bends',
  'seated-knee-extension': 'Straighten knee, toe up',
  'high-sit-stand': 'Higher seat, press through feet',
  'low-step-up': 'Whole foot on step, knee over toes',
  'mini-squat': 'Mini squat by support, knees with toes',
  'slow-knee-extension': 'Straighten slowly, lower 3s',
  'chair-squat-knee': 'Chair squat, steady pace',
  'step-down': 'Slow step down, pelvis level',
  'split-squat': 'Short split, lower a little',
  'weighted-squat': 'Hold weight close, squat controlled',
  'single-leg-sit-stand': 'More weight through one leg',
  'single-leg-sit-stand-loaded': 'Single-leg sit-stand with load',
  'hip-rest': 'Hip supported, breathing easy',
  'hip-rest-supported': 'Hip on pillow, doubly supported',
  'hip-roll': 'Knees rock, pelvis follows gently',
  'glute-set': 'Squeeze buttocks without arching back',
  'hip-abduction-hold': 'Leg out to wall, press gently',
  'seated-hip-rotation': 'Foot in-out, thigh stays',
  'bridge-hip': 'Hip bridge, pelvis level',
  'hip-abduction': 'Lift leg sideways, pelvis still',
  'high-chair-hip': 'Sit-stand from high seat',
  'low-step-hip': 'Step up, whole foot',
  'hinge-hip': 'Hinge from hips, soft knees',
  'single-bridge': 'One leg bridge, hold level',
  'lateral-step-up': 'Side step up, knee tracks',
  'split-squat-hip': 'Split squat, upright torso',
  'weighted-hinge-hip': 'Weight close, hinge',
  'lateral-step-down': 'Side step down, control',
  'lateral-step-down-loaded': 'Side step down with more load',
  'ankle-rest': 'Ankle supported, rest',
  'ankle-rest-supported': 'Ankle on pillow, fully eased',
  'ankle-pump': 'Pump ankle up and down',
  'ankle-circle': 'Gentle ankle circles',
  'calf-hold': 'Heels lifted, hold steady',
  'toe-spread': 'Spread and relax toes',
  'seated-heel-raise': 'Heels rise, seated tall',
  'double-calf': 'Rise onto toes, both feet',
  'band-eversion': 'Foot turns out against band',
  'balance-supported': 'Weight on one foot, fingertips ready',
  'heel-lowering': 'Rise up, lower 3s on level ground',
  'single-calf': 'One foot rise, steady',
  'step-calf': 'Heels off step edge',
  'balance-reach': 'Reach while balanced',
  'loaded-calf': 'Calf raise with load',
  'quick-calf': 'Quick spring, still controlled',
  'quick-calf-loaded': 'Quick calf with added load',
  'wrist-rest': 'Forearm supported, wrist neutral',
  'wrist-rest-supported': 'Forearm on extra pillow, neutral',
  'wrist-circle': 'Slow wrist circles, elbow still',
  'wrist-hold-extension': 'Wrist holds against other hand',
  'hand-open': 'Open and close hand gently',
  'thumb-slide': 'Thumb slides, wrist neutral',
  'wrist-extension': 'Wrist lifts, forearm supported',
  'wrist-flexion': 'Wrist curls down, control up',
  'forearm-rotation': 'Palm up to down, elbow still',
  'towel-grip': 'Light towel squeeze, then relax',
  'eccentric-wrist': 'Lift with help, lower slowly 3s',
  'loaded-wrist-extension': 'Wrist extension with weight',
  'loaded-wrist-flexion': 'Wrist flexion with weight',
  'towel-twist': 'Twist towel, gentle resistance',
  'farmer-carry-elbow': 'Hold and walk, shoulders set',
  'pinch-release': 'Pinch and release, light grip',
  'pinch-release-loaded': 'Pinch with more resistance',
  'rib-breathing': 'Hands on ribs, widen with inhale',
  'rib-breathing-supported': 'Hands on ribs, pillow eased',
  'shoulder-roll-upper': 'Shoulder rolls, tall spine',
  'thoracic-rotation': 'Upper back twists, pelvis still',
  'scap-upper': 'Blades set down and together',
  'chest-opening': 'Open chest gently, no forcing',
  'thoracic-extension': 'Lift chest a little over chair back',
  'open-book': 'Side-lying, arm opens like a book',
  'wall-slide-upper': 'Arms slide up wall, neck easy',
  'band-row-upper': 'Band row, elbows low',
  'thoracic-rotation-standing': 'Rotate upper back while standing',
  'band-pullapart-upper': 'Band pull-apart, pinch blades',
  'prone-arm-lift': 'Lying, arm lifts a little',
  'resisted-row-upper': 'Resisted row, slow return',
  'rotation-press': 'Rotate then press gently',
  'overhead-reach-upper': 'Reach up, ribs down',
  'overhead-reach-upper-loaded': 'Overhead reach with light load',
};

const labelAr: Record<string, string> = {
  'breathe-supine': 'تنفّس في الأضلاع ودع البطن يرتاح',
  'breathe-supine-supported': 'تنفّس مع وسادة إضافية براحة أكبر',
  'pelvic-tilt': 'حرّك الحوض بلطف وسوّ سطح أسفل الظهر',
  'knee-rock': 'حرّك الركبتين جانبا بمدى صغير',
  'prone-press': 'اتكئ على الساعدين وابق الحوض مرتاحا',
  'brace-supine': 'شدّ البطن بخفة كاستعداد لدفعة',
  'heel-slide': 'اسحب الكعب نحوك ثم أبعده بتحكم',
  'bridge': 'ادفع عبر القدمين وارفع الحوض بلا تقوّس',
  'birddog-prep': 'مدّ ساقا للخلف مع ثبات الحوض',
  'sit-stand': 'اتكئ قليلا للأمام وانهض عبر القدمين',
  'hinge': 'ادفع الوركين للخلف ثم انهض',
  'bridge-march': 'حافظ على الجسر وارفع ركبة قليلا',
  'birddog-full': 'مدّ ذراعا وساقا متعاكستين بثبات',
  'chair-squat': 'اجلس للخلف كأنك تجلس على كرسي',
  'weighted-hinge': 'انحن مع حمل قريب وظهر مستقيم',
  'suitcase-carry': 'قف منتصبا واحمل وامش بثبات',
  'suitcase-carry-loaded': 'احمل أثقل قليلا بنفس الوضعية',
  'neck-rest': 'ادعم الرقبة ودع العضلات ترتاح',
  'neck-rest-supported': 'الرقبة على منشفة بدعم كامل',
  'neck-turn': 'التف بالرأس قليلا مع حركة العين',
  'chin-nod': 'إيماءة صغيرة للأسفل بلا بروز ذقن',
  'neck-hold-rotate': 'اضغط الرأس على اليد بثبات',
  'shoulder-roll': 'حرّك الكتفين للخلف والأسفل',
  'chin-tuck': 'اسحب الذقن للخلف وأطِل الرقبة',
  'neck-rotate-full': 'دوران كامل ضمن الراحة',
  'neck-isometric': 'اضغط الرأس على اليد دون حركة',
  'wall-slide': 'حرّك الساعدين على الجدار',
  'band-row': 'اسحب المرفقين للخلف',
  'chin-tuck-standing': 'سحب الذقن وقوفا',
  'resisted-rotation': 'قاوم الدوران باليد',
  'incline-push': 'ادفع صدرك عن الجدار',
  'band-pullapart': 'افتح الشريط على مستوى الصدر',
  'overhead-reach': 'مدّ الذراع للأعلى برفق',
  'overhead-reach-loaded': 'مدّ مع حمل خفيف',
  'shoulder-rest': 'ادعم الذراع ودع الكتف يرتاح',
  'shoulder-rest-supported': 'الذراع على وسادة براحة تامة',
  'pendulum': 'دع الذراع يتدلى وتمايل بالجسم',
  'table-slide': 'حرّك اليد للأمام على المنشفة',
  'scap-set': 'قرّب لوحي الكتف بلطف',
  'er-hold': 'المرفق بجانبك واضغط للخارج',
  'assisted-elevation': 'ساعد الذراع الأخرى على الرفع',
  'wall-slide-shoulder': 'حرّك الذراع على الجدار ضمن الراحة',
  'band-er': 'أدر الساعد للخارج ضد الشريط',
  'scaption': 'ارفع بزاوية الكتف وإبهام لأعلى',
  'wall-push': 'ادفع الحائط ببطء',
  'er-standing': 'دوران خارجي وقوفا',
  'band-row-shoulder': 'سحب الشريط والمرفق قريب',
  'incline-push-shoulder': 'ضغط مائل والجسم مستقيم',
  'weighted-scaption': 'رفع بوزن خفيف وتحكم ٣ث',
  'overhead-press': 'ادفع للأعلى والرقبة مرتاحة',
  'overhead-press-loaded': 'ادفع بحمل أكثر قليلا',
  'knee-rest': 'ادعم الركبة ودعها ترتاح',
  'knee-rest-supported': 'الركبة على وسادة بدعم كامل',
  'knee-extension-hold': 'شدّ الفخذ وافرد الركبة بلطف',
  'heel-slide-knee': 'اسحب الكعب واثن الركبة',
  'quad-set': 'اضغط الركبة للأسفل',
  'seated-knee-bend': 'حرّك القدم للخلف',
  'seated-knee-extension': 'افرد الركبة وأصابع القدم لأعلى',
  'high-sit-stand': 'انهض من كرسي مرتفع',
  'low-step-up': 'قدم كاملة على الدرجة',
  'mini-squat': 'قرفصاء مصغر بجانب دعم',
  'slow-knee-extension': 'افرد ببطء واخفض ٣ث',
  'chair-squat-knee': 'قرفصاء كرسي بإيقاع ثابت',
  'step-down': 'انزل ببطء والحوض مستوٍ',
  'split-squat': 'وضع منقسم واخفض قليلا',
  'weighted-squat': 'احمل ثقلا قريبا',
  'single-leg-sit-stand': 'حمل أكثر على ساق واحدة',
  'single-leg-sit-stand-loaded': 'ساق واحدة مع حمل',
  'hip-rest': 'ادعم الورك وتنفس بهدوء',
  'hip-rest-supported': 'الورك على وسادة بدعم مضاعف',
  'hip-roll': 'تمايل الركبتان مع الحوض',
  'glute-set': 'شدّ الألية بلا تقوّس ظهر',
  'hip-abduction-hold': 'اضغط الساق على الجدار',
  'seated-hip-rotation': 'حرّك القدم للداخل والخارج',
  'bridge-hip': 'جسر الورك بحوض مستوٍ',
  'hip-abduction': 'ارفع الساق جانبا',
  'high-chair-hip': 'انهض من كرسي مرتفع',
  'low-step-hip': 'اصعد بكامل القدم',
  'hinge-hip': 'انحن من الوركين',
  'single-bridge': 'جسر بساق واحدة',
  'lateral-step-up': 'اصعد جانبيا',
  'split-squat-hip': 'قرفصاء منقسم وجذع مستقيم',
  'weighted-hinge-hip': 'انحن مع وزن',
  'lateral-step-down': 'انزل جانبيا بتحكم',
  'lateral-step-down-loaded': 'نزول جانبي مع حمل',
  'ankle-rest': 'ادعم الكاحل',
  'ankle-rest-supported': 'الكاحل على وسادة براحة تامة',
  'ankle-pump': 'حرّك الكاحل لأعلى وأسفل',
  'ankle-circle': 'دوائر كاحل لطيفة',
  'calf-hold': 'ارفع العقبين وثبّت',
  'toe-spread': 'افتح الأصابع وارتح',
  'seated-heel-raise': 'ارفع العقبين جلوسا',
  'double-calf': 'ارتفع على أطراف القدمين',
  'band-eversion': 'أدر القدم للخارج ضد الشريط',
  'balance-supported': 'قف على ساق واحدة بدعم',
  'heel-lowering': 'ارتفع واخفض ٣ث',
  'single-calf': 'ارتفع بساق واحدة',
  'step-calf': 'عقبان خارج الحافة',
  'balance-reach': 'توازن ومدّ الذراع',
  'loaded-calf': 'رفع ربلة بحمل',
  'quick-calf': 'حركة زنبركية سريعة',
  'quick-calf-loaded': 'حركة سريعة مع حمل',
  'wrist-rest': 'اسند الساعد والرسغ محايد',
  'wrist-rest-supported': 'الساعد على وسادة إضافية محايد',
  'wrist-circle': 'دوائر رسغ بطيئة',
  'wrist-hold-extension': 'ثبّت الرسغ ضد اليد',
  'hand-open': 'افتح وأغلق اليد',
  'thumb-slide': 'حرّك الإبهام',
  'wrist-extension': 'ارفع الرسغ',
  'wrist-flexion': 'اثن الرسغ للأسفل',
  'forearm-rotation': 'أدر الساعد',
  'towel-grip': 'اعصر منشفة بخفة',
  'eccentric-wrist': 'ارفع بمساعدة واخفض ببطء',
  'loaded-wrist-extension': 'مدّ رسغ مع وزن',
  'loaded-wrist-flexion': 'ثني رسغ مع وزن',
  'towel-twist': 'اعصر منشفة بمقاومة',
  'farmer-carry-elbow': 'احمل وامش بثبات',
  'pinch-release': 'اقرص واترك',
  'pinch-release-loaded': 'اقرص بمقاومة أكبر',
  'rib-breathing': 'يداك على الأضلاع وتوسع بالشهيق',
  'rib-breathing-supported': 'يداك على الأضلاع مع وسادة',
  'shoulder-roll-upper': 'لف الكتفين وطوّل العمود',
  'thoracic-rotation': 'التف بالصدر والحوض ثابت',
  'scap-upper': 'ثبّت لوحي الكتف للأسفل',
  'chest-opening': 'افتح الصدر بلطف',
  'thoracic-extension': 'ارفع الصدر قليلا',
  'open-book': 'جانبا ككتاب مفتوح',
  'wall-slide-upper': 'انزلق الذراعان على الجدار',
  'band-row-upper': 'سحب شريط والمرفقان منخفضان',
  'thoracic-rotation-standing': 'دوران صدري وقوفا',
  'band-pullapart-upper': 'شد الشريط وقرّب الألواح',
  'prone-arm-lift': 'مستلق على البطن وارفع ذراعا',
  'resisted-row-upper': 'سحب بمقاومة وعودة بطيئة',
  'rotation-press': 'دوران ثم دفع بلطف',
  'overhead-reach-upper': 'مدّ للأعلى والأضلاع للأسفل',
  'overhead-reach-upper-loaded': 'مدّ علوي مع حمل خفيف',
};

function baseKeyOf(key: string) {
  return key.replace('-supported', '');
}

/** Bilingual per-exercise movement cue, e.g. "Heels rise, seated tall". */
export function captionFor(exercise: Exercise, arabic: boolean): string {
  const key = animationFor[exercise.id] || 'hinge';
  const bKey = baseKeyOf(key);
  return arabic
    ? (labelAr[key] || labelAr[bKey] || exercise.nameAr)
    : (labelEn[key] || labelEn[bKey] || exercise.name);
}
