import json,os
os.makedirs('src/data',exist_ok=True)
def write(name,data):json.dump(data,open('src/data/'+name+'.json','w'),ensure_ascii=False,indent=2)
groups={
'lower-back':[('back-flexion','Back pain that prefers bending','Your back is sensitive to sustained arching or standing. Comfortable bending and gradually rebuilding strength may help.',['arching','standing'],['bending']),('back-extension','Back pain that prefers straightening','Sitting and bending seem to irritate your back. Short, comfortable movement in the opposite direction may help.',['bending','sitting','lifting'],['arching']),('lumbar-radicular','Back pain with sensitive leg nerves','A sensitive nerve can cause pain or tingling that travels into a leg. Start with movements that keep symptoms closer to your back, not farther down your leg.',['tingling','leg'],[]),('si-joint','Pain around the back of your pelvis','Pain close to the pelvic joints can be sensitive to uneven loading. Comfortable, even-sided movement and gradual hip strength may help.',['stairs','one-leg'],[])],
'neck':[('neck-mechanical','A sensitive, stiff neck','Neck movement can become uncomfortable after an awkward load or position. Gentle movement and gradual strength usually help.',['turning'],[]),('neck-postural','Neck discomfort with sustained positions','Long periods in one position can tire the neck and shoulders. Regular movement breaks matter more than finding a perfect posture.',['sitting','desk'],[]),('neck-headache','Headache linked to neck movement','Some headaches change with neck position or movement. Easy neck mobility can help, but new or unusual headaches need an assessment.',['headache'],[]),('cervical-radicular','Neck pain with sensitive arm nerves','Pain or tingling travelling into the arm can reflect nerve sensitivity. Avoid movements that spread symptoms farther down the arm.',['tingling','arm'],[])],
'shoulder':[('rotator-cuff','A shoulder sensitive to load','The muscles and tendons supporting your shoulder may be sensitive to reaching and lifting. A manageable amount of loading can build their tolerance.',['lifting','reaching'],[]),('subacromial','Pain when raising your arm','Reaching overhead can irritate a sensitive shoulder. Comfortable movement and gradual shoulder strength can improve confidence and capacity.',['overhead'],[]),('frozen-shoulder','A shoulder becoming stiff in several directions','A slowly stiffening shoulder, including difficulty turning the arm outwards, can need a gentler approach. Avoid forcing stretches or heavy strengthening while it is very painful.',['stiff-all','dressing'],[]),('ac-joint','Pain at the top of your shoulder','The small joint at the top of your shoulder can be sensitive to crossing your arm or lying on that side. Adjust the load while keeping comfortable movement.',['cross-body','side-lying'],[])],
'knee':[('patellofemoral','Pain around the kneecap','Stairs, squats or long sitting can be uncomfortable when the kneecap area is sensitive. Gradual hip and knee loading can build tolerance.',['stairs','squatting','sitting'],[]),('patellar-tendon','A kneecap tendon sensitive to load','Jumping and faster loading can irritate the tendon below the kneecap. Start with manageable loading, then rebuild spring and speed.',['jumping','running'],[]),('meniscal','A knee sensitive to twisting','A sensitive knee can dislike deep bending and rotation. Comfortable movement and strength help; true locking needs an assessment.',['twisting','deep-bend'],[]),('knee-oa','A stiff knee that eases with movement','A knee that stiffens after rest often benefits from regular gentle movement and progressive strength. Symptoms do not tell us how much structural change is present.',['morning','walking'],[])],
'hip':[('gluteal-tendon','Pain on the outside of your hip','The outer hip tendons may be sensitive to compression and load. Avoid hanging on one hip and build strength without squeezing the painful side.',['side-lying','one-leg'],[]),('hip-oa','A hip that feels stiff after rest','Hip stiffness often responds to regular comfortable movement and strength. Keep useful movement in your day and build gradually.',['morning','walking'],[]),('groin-strain','A groin sensitive after activity','The muscles around your groin can become sensitive after a change in activity or a strain. Begin with easy contractions before returning to faster movements.',['running','incident'],[])],
'ankle':[('ankle-sprain','An ankle recovering from a twist','After a twist, comfortable motion and gradually returning weight through the ankle can help. Major swelling or inability to bear weight needs assessment.',['incident','twisting'],[]),('achilles','An Achilles tendon sensitive to load','The tendon behind the ankle may be sensitive to sudden increases in walking or running. Consistent slow calf loading builds tolerance.',['running','heel-raise'],[]),('plantar-heel','Heel pain on your first steps','The tissues under the heel may be sensitive after rest and long periods of standing. Comfortable foot and calf loading can help.',['morning','standing'],[])],
'elbow':[('lateral-elbow','Pain on the outside of your elbow','Gripping and lifting may irritate the muscles attaching to the outer elbow. Adjust the grip load and rebuild wrist strength.',['gripping','lifting'],[]),('medial-elbow','Pain on the inside of your elbow','Pulling and wrist bending can irritate the inner elbow. Gradual forearm loading and activity changes can build tolerance.',['pulling','wrist-flexion'],[]),('de-quervain','Pain on the thumb side of your wrist','Thumb and wrist tendons can become sensitive with repetitive use. Reduce prolonged pinching and begin comfortable movement.',['thumb','pinching'],[]),('carpal-tunnel','Tingling into the hand','A sensitive nerve at the wrist can cause hand tingling, often at night. Keep the wrist comfortable and seek assessment for persistent numbness or weakness.',['tingling','night'],[])],
'upper-back':[('thoracic','A stiff, sensitive upper back','Your upper back can become sensitive to sustained positions and unfamiliar loads. Easy rotation, breathing and strength can help.',['sitting','turning'],[]),('rib','Rib-area pain with movement','Muscles and joints around the ribs can become sensitive to twisting and deep breathing. Keep movement easy; chest pain or breathlessness needs prompt assessment.',['breathing','twisting'],[])]}
presentations=[];rules=[]
for group,items in groups.items():
 for i,(id,name,ex,agg,ease) in enumerate(items):
  presentations.append({'id':id,'group':group,'name':name,'explanation':ex,'course':'Often improves over several weeks with a manageable, consistent routine. Persistent symptoms can still improve; progress is not always linear.' if id!='frozen-shoulder' else 'Often changes over many months. Comfort and useful movement matter more than forcing range.','helps':'Start with a dose you can recover from. Use the next-morning response to guide load, then build strength gradually.','nameAr':{'lower-back':'نمط ألم أسفل الظهر','neck':'نمط ألم الرقبة','shoulder':'نمط ألم الكتف','knee':'نمط ألم الركبة','hip':'نمط ألم الورك','ankle':'نمط ألم الكاحل','elbow':'نمط ألم الذراع','upper-back':'نمط ألم أعلى الظهر'}[group]})
  rules.append({'presentationId':id,'group':group,'baseScore':3 if i==0 else 1,'aggravators':{a:4 for a in agg},'easers':{a:3 for a in ease},'neuroWeight':7 if 'radicular' in id or id=='carpal-tunnel' else -1,'gradualWeight':4 if id=='frozen-shoulder' else 0,'incidentWeight':5 if id in ['ankle-sprain','groin-strain','meniscal'] else 0})
write('presentations',presentations);write('matching-rules',rules)
reg=json.load(open('/tmp/region-colors.json'));regions=[]
ar={'lower-back':'أسفل الظهر','upper-back':'أعلى الظهر','neck':'الرقبة','shoulder':'الكتف','knee':'الركبة','hip':'الورك','ankle':'الكاحل','elbow':'المرفق','wrist':'الرسغ','foot':'القدم','hand':'اليد'}
for id in reg['names']:
 part=id.replace('-left','').replace('-right','');side='left' if id.endswith('-left') else 'right' if id.endswith('-right') else 'center'
 group=part if part in groups else {'forehead':'neck','jaw':'neck','chest':'upper-back','abdomen':'lower-back','upper-arm':'shoulder','forearm':'elbow','wrist':'elbow','hand':'elbow','thigh':'hip','calf':'ankle','foot':'ankle'}.get(part,'lower-back')
 y={'forehead':1.72,'jaw':1.6,'neck':1.49,'shoulder':1.43,'upper-arm':1.26,'chest':1.3,'upper-back':1.3,'elbow':1.1,'forearm':.96,'wrist':.84,'hand':.72,'abdomen':1.12,'lower-back':1.12,'hip':.9,'thigh':.68,'knee':.48,'calf':.3,'ankle':.12,'foot':.04}[part]
 x=(.3 if part in ['shoulder','upper-arm'] else .4 if part in ['elbow','forearm','wrist','hand'] else .12)*(1 if side=='left' else -1 if side=='right' else 0)
 regions.append({'id':id,'maskColor':reg['colors'][id],'label':part.replace('-',' ').title()+(' · '+side.title() if side!='center' else ''),'labelAr':ar.get(part,'منطقة الجسم')+(' · يسار' if side=='left' else ' · يمين' if side=='right' else ''),'side':side,'view':'back' if part in ['lower-back','upper-back'] else 'both','group':group,'focusTarget':[x,y,-.1 if 'back' in part else .1],'focusDistance':1.8,'neighbours':[],'presentationIds':[p['id'] for p in presentations if p['group']==group]})
for r in regions:r['neighbours']=[x['id'] for x in regions if x['group']==r['group'] and x['id']!=r['id']][:3]
write('regions',regions)
# Fifteen named movements per regional family; all variant links remain within a clinically compatible family.
names={
'lower-back':['Supported belly breathing','Small pelvic tilts','Gentle knee rocks','Supported back extension','Supine abdominal brace','Heel slides','Bridge','Bird dog preparation','Sit to stand','Standing hip hinge','Bridge march','Bird dog','Chair squat','Loaded hip hinge','Suitcase carry'],
'neck':['Supported neck rest','Small neck turns','Gentle chin nod','Neck rotation hold','Seated shoulder rolls','Chin tuck','Seated neck rotation','Neck isometric press','Wall slide','Band row','Standing chin tuck','Resisted neck rotation','Incline wall press','Band pull apart','Overhead reach'],
'shoulder':['Supported shoulder rest','Small pendulum','Table slide','Shoulder blade setting','External rotation hold','Assisted arm elevation','Wall slide','Band external rotation','Light scaption','Wall push up','Standing external rotation','Band row','Incline push up','Weighted scaption','Overhead press'],
'knee':['Supported knee rest','Knee extension hold','Heel slide','Gentle quadriceps squeeze','Seated knee bend','Seated knee extension','High chair sit to stand','Low step up','Supported mini squat','Slow knee extension','Chair squat','Step down','Split squat','Weighted squat','Single leg sit to stand'],
'hip':['Supported hip rest','Small hip rolls','Gluteal squeeze','Supported hip abduction hold','Seated hip rotation','Bridge','Standing hip abduction','High chair sit to stand','Low step up','Supported hip hinge','Single leg bridge','Lateral step up','Split squat','Weighted hip hinge','Lateral step down'],
'ankle':['Supported ankle rest','Small ankle pumps','Ankle circles','Seated calf hold','Gentle toe spread','Seated heel raise','Double leg calf raise','Band ankle eversion','Supported balance','Slow heel lowering','Single leg calf raise','Step calf raise','Single leg balance reach','Loaded calf raise','Quick calf raise'],
'elbow':['Supported wrist rest','Small wrist circles','Wrist extension hold','Gentle hand opening','Thumb slide','Wrist extension','Wrist flexion','Forearm rotation','Gentle towel grip','Slow wrist lowering','Loaded wrist extension','Loaded wrist flexion','Resisted forearm rotation','Farmer carry','Pinch and release'],
'upper-back':['Supported rib breathing','Small shoulder rolls','Seated gentle rotation','Shoulder blade setting','Supported chest opening','Seated thoracic extension','Side lying open book','Wall slide','Band row','Standing thoracic rotation','Band pull apart','Prone arm lift','Resisted row','Standing rotation press','Overhead reach']}
ex=[]
for group,ns in names.items():
 ids=[p['id'] for p in presentations if p['group']==group]
 for i,name in enumerate(ns):
  phase=1 if i<5 else 2 if i<10 else 3;typ='isometric' if any(s in name.lower() for s in ['hold','squeeze','brace','setting']) else 'mobility' if phase==1 or any(s in name.lower() for s in ['rotation','slide','circle','breathing']) else 'eccentric' if 'lowering' in name else 'strength'
  id=group+'-'+str(i+1);target=[r['id'] for r in regions if r['group']==group][:2]
  cues=['Settle into a comfortable starting position.','Move slowly through a range that feels manageable.','Keep breathing; avoid holding your breath.','Stop if symptoms spread or new tingling appears.']
  if 'hold' in name.lower():cues[1]='Press gently without moving the joint; keep the effort comfortable.'
  ex.append({'id':id,'name':name,'nameAr':{'isometric':'تمرين ثبات لطيف','mobility':'حركة لطيفة للمفصل','strength':'تمرين تقوية تدريجي','eccentric':'خفض بطيء ومتحكم'}[typ],'presentationIds':ids,'phase':phase,'targetRegions':target,'type':typ,'sets':5 if typ=='isometric' else 2 if typ=='mobility' else 3,'reps':10 if typ!='isometric' else 0,'holdSeconds':30 if typ=='isometric' else 0,'tempo':'3 seconds down' if typ in ['strength','eccentric'] else 'Slow and comfortable','restSeconds':30,'frequencyPerWeek':7 if phase==1 else 4,'equipment':'band' if 'Band' in name or 'band' in name else 'weight' if 'Weighted' in name or 'Loaded' in name else 'chair' if 'chair' in name.lower() or 'Seated' in name else 'wall' if 'Wall' in name else 'none','positionRequired':'seated' if 'Seated' in name else 'lying' if group=='lower-back' and i<8 else 'standing','cues':cues,'commonMistakes':['Forcing the movement into pain.','Rushing or holding your breath.'],'easierVariantId':group+'-'+str(max(1,i)),'harderVariantId':group+'-'+str(min(15,i+2)),'contraindicatedFor':['frozen-shoulder'] if group=='shoulder' and phase>1 else ['back-flexion'] if name=='Supported back extension' else [],'media':{'video':None,'thumbnail':None,'highlightRegions':target}})
write('exercises',ex)
# Keep public-domain source examples separate; not auto-prescribed gym exercises.
source=json.load(open('/tmp/exercises.json'))
selected=[x for x in source if x['name'] in ['Bird Dog','Glute Bridge','Standing Calf Raises','Wrist Curls','Seated Calf Raise']]
write('open-source-reference',selected)
write('demo',{'label':'Sample recovery journey','pain':[6,6,5,5,4,5,4,4,3,4,3,3,3,2],'sessions':8,'planned':10,'streak':3,'phase':1})
print(len(presentations),'presentations',len(regions),'regions',len(ex),'exercises')
