import { chromium } from '@playwright/test';
const browser=await chromium.launch({headless:true,args:['--no-sandbox','--enable-webgl','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
const page=await browser.newPage({viewport:{width:1440,height:1050},deviceScaleFactor:1});
const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')console.log('CONSOLE',m.text().slice(0,400));});
await page.goto('http://localhost:3000');await page.waitForTimeout(6000);await page.screenshot({path:'/tmp/kinesio-desktop.png',fullPage:true});
console.log('CANVAS',await page.locator('canvas').count());
await page.getByRole('button',{name:'Lower back',exact:true}).click();await page.waitForTimeout(1600);await page.screenshot({path:'/tmp/kinesio-selected.png',fullPage:true});
await page.getByRole('button',{name:'Yes, let’s continue',exact:true}).click();
for(let step=0;step<6;step++){if(step===4)await page.getByRole('button',{name:'Bending forward',exact:true}).first().click();if(step===5)await page.getByRole('button',{name:'Very little sets it off',exact:false}).click();await page.getByRole('button',{name:'Continue',exact:true}).click();}
await page.getByRole('button',{name:'Understand my pain',exact:true}).click();
await page.getByRole('button',{name:'Let’s build my plan',exact:true}).click();
await page.getByRole('button',{name:'See my personal programme',exact:true}).click();
console.log('PROGRAMME',await page.locator('.exercise-info h3').allTextContents());
await page.getByRole('button',{name:'Start my session',exact:true}).click();await page.getByRole('button',{name:'Got it. Let’s move.',exact:true}).click();
const before=await page.locator('.session-instructions h1').innerText();await page.getByRole('button',{name:'Too painful',exact:true}).click();console.log('SWAP',before,'→',await page.locator('.session-instructions h1').innerText());
for(let i=0;i<3;i++)await page.getByRole('button',{name:'Next exercise',exact:true}).click();await page.getByRole('button',{name:'Finish & check in',exact:true}).click();await page.getByRole('button',{name:'Save & finish',exact:true}).click();
await page.waitForTimeout(1500);const saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('kinesio-recovery')));console.log('SAVED',saved.logs.length,saved.intake.irritability);
await page.getByRole('button',{name:'My progress',exact:true}).click();await page.waitForTimeout(1000);await page.screenshot({path:'/tmp/kinesio-progress.png',fullPage:true});
await page.getByRole('button',{name:'Your body',exact:true}).click();await page.setViewportSize({width:390,height:844});await page.waitForTimeout(1500);await page.screenshot({path:'/tmp/kinesio-mobile.png',fullPage:true});
console.log('OVERFLOW',await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth));
console.log('ERRORS',errors);await browser.close();
if(errors.length)process.exit(1);
